# Copyright (C) 2020 Free Software Foundation, Inc.
#
# This file is part of DejaGnu.
#
# DejaGnu is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# DejaGnu is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DejaGnu; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.

# Cause a divide-by-zero error in an auto-loaded procedure.

pass "running error-al-dbz.exp"

set fd [open [testsuite file -object -test lib foo.tcl] w]
puts $fd {proc throw_arith_error_div_by_zero { } {
    expr { 1 / 0 }
}
}
close $fd

auto_mkindex \
    [testsuite file -object -test lib] \
    [testsuite file -object -test lib/*.tcl]

lappend auto_path [testsuite file -object -test lib]

throw_arith_error_div_by_zero

fail "script did not abort"
